// <auto-generated />
using System;
using GoldSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoldSystem.Data.Migrations
{
    [DbContext(typeof(GoldDbContext))]
    [Migration("20260316172817_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GoldSystem.Data.Entities.AuditLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewValueJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValueJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("TableName", "RecordId");

                    b.ToTable("AuditLogs", t =>
                        {
                            t.HasComment("Append-only audit log. No updates or deletes permitted.");
                        });
                });

            modelBuilder.Entity("GoldSystem.Data.Entities.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillId"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalanceDue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("BillDate")
                        .HasColumnType("date");

                    b.Property<string>("BillNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<decimal>("CGST")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExchangeValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GoldValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IGST")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<decimal>("MakingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("RateSnapshot22K")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RateSnapshot24K")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RoundOff")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SGST")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("StoneCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxableAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("WastageAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BillId");

                    b.HasIndex("BillDate");

                    b.HasIndex("BillNo")
                        .IsUnique();

                    b.HasIndex("BranchId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("GoldSystem.Data.Entities.BillItem", b =>
                {
                    b.Property<int>("BillItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillItemId"));

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<decimal>("BillableWeight")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("CGST_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GoldValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrossWeight")
                        .HasColumnType("decimal(10,3)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MakingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MakingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("MakingValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetWeight")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("PureGoldWeight")
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("Purity")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal>("RateUsed24K")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SGST_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StoneCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StoneWeight")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("TaxableAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WastagePercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("WastageWeight")
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("BillItemId");

                    b.HasIndex("BillId");

                    b.HasIndex("ItemId");

                    b.ToTable("BillItems");
                });

            modelBuilder.Entity("GoldSystem.Data.Entities.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GSTIN")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOwnerBranch")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SqlConnectionString")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("BranchId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            BranchId = 1,
                            Address = "Head Office Address",
                            Code = "HO",
                            GSTIN = "000000000000000",
                            IsActive = true,
                            IsOwnerBranch = true,
                            Name = "Head Office",
                            Phone = "0000000000",
                            SqlConnectionString = ""
                        });
                });

            modelBuilder.Entity("GoldSystem.Data.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("DefaultMakingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("DefaultMakingValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DefaultPurity")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal>("DefaultWastagePercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("HUIDRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("SortOrder");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            DefaultMakingType = "PERCENT",
                            DefaultMakingValue = 12m,
                            DefaultPurity = "22K",
                            DefaultWastagePercent = 2m,
                            HUIDRequired = true,
                            IsActive = true,
                            Name = "Ring",
                            SortOrder = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            DefaultMakingType = "PERCENT",
                            DefaultMakingValue = 10m,
                            DefaultPurity = "22K",
                            DefaultWastagePercent = 2m,
                            HUIDRequired = true,
                            IsActive = true,
                            Name = "Chain",
                            SortOrder = 2
                        },
                        new
                        {
                            CategoryId = 3,
                            DefaultMakingType = "PERCENT",
                            DefaultMakingValue = 12m,
                            DefaultPurity = "22K",
                            DefaultWastagePercent = 2m,
                            HUIDRequired = true,
                            IsActive = true,
                            Name = "Bangle",
                            SortOrder = 3
                        },
                        new
                        {
                            CategoryId = 4,
                            DefaultMakingType = "PERCENT",
                            DefaultMakingValue = 15m,
                            DefaultPurity = "22K",
                            DefaultWastagePercent = 2m,
                            HUIDRequired = true,
                            IsActive = true,
                            Name = "Earring",
                            SortOrder = 4
                        },
                        new
                        {
                            CategoryId = 5,
                            DefaultMakingType = "PERCENT",
                            DefaultMakingValue = 12m,
                            DefaultPurity = "22K",
                            DefaultWastagePercent = 2m,
                            HUIDRequired = true,
                            IsActive = true,
                            Name = "Pendant",
                            SortOrder = 5
                        },
                        new
                        {
                            CategoryId = 6,
                            DefaultMakingType = "PERCENT",
                            DefaultMakingValue = 10m,
                            DefaultPurity = "22K",
                            DefaultWastagePercent = 2m,
                            HUIDRequired = true,
                            IsActive = true,
                            Name = "Necklace",
                            SortOrder = 6
                        },
                        new
                        {
                            CategoryId = 7,
                            DefaultMakingType = "PERCENT",
                            DefaultMakingValue = 10m,
                            DefaultPurity = "22K",
                            DefaultWastagePercent = 2m,
                            HUIDRequired = false,
                            IsActive = true,
                            Name = "Kada",
                            SortOrder = 7
                        });
                });

            modelBuilder.Entity("GoldSystem.Data.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CreditLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GSTIN")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("LoyaltyPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("TotalPurchased")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("CustomerId");

                    b.HasIndex("BranchId");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("GoldSystem.Data.Entities.GoldRate", b =>
                {
                    b.Property<int>("RateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RateId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsManualOverride")
                        .HasColumnType("bit");

                    b.Property<string>("OverrideNote")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Rate18K")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rate22K")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rate24K")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("RateDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("RateTime")
                        .HasColumnType("time");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RateId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("RateDate");

                    b.HasIndex("BranchId", "RateDate");

                    b.ToTable("GoldRates");
                });

            modelBuilder.Entity("GoldSystem.Data.Entities.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GrossWeight")
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("HUID")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("MakingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("MakingValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("NetWeight")
                        .HasColumnType("decimal(10,3)");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<decimal>("PurchaseRate24K")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PureGoldWeight")
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("Purity")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int?>("SoldBillId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("StoneWeight")
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("TagNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.Property<decimal>("WastagePercent")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ItemId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("HUID")
                        .IsUnique()
                        .HasFilter("[HUID] IS NOT NULL");

                    b.HasIndex("SoldBillId");

                    b.HasIndex("Status");

                    b.HasIndex("TagNo");

                    b.HasIndex("VendorId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("GoldSystem.Data.Entities.OldGoldExchange", b =>
                {
                    b.Property<int>("ExchangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExchangeId"));

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("ExchangeRateApplied")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExchangeValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrossWeight")
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TestPurity")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("ExchangeId");

                    b.HasIndex("BillId");

                    b.ToTable("OldGoldExchanges");
                });

            modelBuilder.Entity("GoldSystem.Data.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PaymentId");

                    b.HasIndex("BillId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("GoldSystem.Data.Entities.SyncQueue", b =>
                {
                    b.Property<long>("QueueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("QueueId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("QueueId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("SyncQueues");
                });

            modelBuilder.Entity("GoldSystem.Data.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("BranchId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            BranchId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "System Admin",
                            PasswordHash = "CHANGE_ON_FIRST_LOGIN",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            BranchId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Branch Manager",
                            PasswordHash = "CHANGE_ON_FIRST_LOGIN",
                            Role = "Manager",
                            Username = "manager"
                        },
                        new
                        {
                            UserId = 3,
                            BranchId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Sales Operator",
                            PasswordHash = "CHANGE_ON_FIRST_LOGIN",
                            Role = "Operator",
                            Username = "operator"
                        });
                });

            modelBuilder.Entity("GoldSystem.Data.Entities.Vendor", b =>
                {
                    b.Property<int>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendorId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GSTIN")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("OpeningBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("VendorId");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("GoldSystem.Data.Entities.AuditLog", b =>
                {
                    b.HasOne("GoldSystem.Data.Entities.Branch", "Branch")
                        .WithMany("AuditLogs")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoldSystem.Data.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoldSystem.Data.Entities.Bill", b =>
                {
                    b.HasOne("GoldSystem.Data.Entities.Branch", "Branch")
                        .WithMany("Bills")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoldSystem.Data.Entities.Customer", "Customer")
                        .WithMany("Bills")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoldSystem.Data.Entities.User", "User")
                        .WithMany("Bills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoldSystem.Data.Entities.BillItem", b =>
                {
                    b.HasOne("GoldSystem.Data.Entities.Bill", "Bill")
                        .WithMany("BillItems")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoldSystem.Data.Entities.Item", "Item")
                        .WithMany("BillItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("GoldSystem.Data.Entities.Customer", b =>
                {
                    b.HasOne("GoldSystem.Data.Entities.Branch", "Branch")
                        .WithMany("Customers")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("GoldSystem.Data.Entities.GoldRate", b =>
                {
                    b.HasOne("GoldSystem.Data.Entities.Branch", "Branch")
                        .WithMany("GoldRates")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoldSystem.Data.Entities.User", "CreatedByUser")
                        .WithMany("GoldRates")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("GoldSystem.Data.Entities.Item", b =>
                {
                    b.HasOne("GoldSystem.Data.Entities.Branch", "Branch")
                        .WithMany("Items")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoldSystem.Data.Entities.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoldSystem.Data.Entities.Bill", "SoldBill")
                        .WithMany("SoldItems")
                        .HasForeignKey("SoldBillId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GoldSystem.Data.Entities.Vendor", "Vendor")
                        .WithMany("Items")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Category");

                    b.Navigation("SoldBill");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("GoldSystem.Data.Entities.OldGoldExchange", b =>
                {
                    b.HasOne("GoldSystem.Data.Entities.Bill", "Bill")
                        .WithMany("OldGoldExchanges")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("GoldSystem.Data.Entities.Payment", b =>
                {
                    b.HasOne("GoldSystem.Data.Entities.Bill", "Bill")
                        .WithMany("Payments")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("GoldSystem.Data.Entities.SyncQueue", b =>
                {
                    b.HasOne("GoldSystem.Data.Entities.Branch", "Branch")
                        .WithMany("SyncQueues")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("GoldSystem.Data.Entities.User", b =>
                {
                    b.HasOne("GoldSystem.Data.Entities.Branch", "Branch")
                        .WithMany("Users")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("GoldSystem.Data.Entities.Bill", b =>
                {
                    b.Navigation("BillItems");

                    b.Navigation("OldGoldExchanges");

                    b.Navigation("Payments");

                    b.Navigation("SoldItems");
                });

            modelBuilder.Entity("GoldSystem.Data.Entities.Branch", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Bills");

                    b.Navigation("Customers");

                    b.Navigation("GoldRates");

                    b.Navigation("Items");

                    b.Navigation("SyncQueues");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("GoldSystem.Data.Entities.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GoldSystem.Data.Entities.Customer", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("GoldSystem.Data.Entities.Item", b =>
                {
                    b.Navigation("BillItems");
                });

            modelBuilder.Entity("GoldSystem.Data.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Bills");

                    b.Navigation("GoldRates");
                });

            modelBuilder.Entity("GoldSystem.Data.Entities.Vendor", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
